#include<stdio.h>
#include<conio.h>
	int main(){
	int num1,num2,num3,num4;
	int max;
	printf("enter four numbers: ");
	scanf("%d %d %d %d", &num1,&num2,&num3,&num4);
	if(num1 >num2) {
	if(num1> num4)
	max = num1;
	} else {
		max = num4;
	}
	}else{
	if(num3 >num4){
	max=num3;
	}else{
	max= num4;
	}
	}
	}else{
	if{num2 > num3){
		if(num2 > num4){
	}else {
		if(num3 >num4) {
		max = num3;
		}else{
			max=num4;
		}
	}
}
	printf("the maximum value is %d\n",max);


